-- ==========================================
-- CHASED: Rebirth P2P Setup
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Create the Items Table
create table if not exists rebirth_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price text not null,
  image_url text not null,
  category text not null,
  seller_name text,
  user_id uuid references auth.users not null
);

-- 2. Enable Row Level Security (RLS)
alter table rebirth_items enable row level security;

-- 3. Policies (Who can do what)
-- Everyone can view items
create policy "Public items are viewable by everyone"
  on rebirth_items for select
  using ( true );

-- Authenticated users can insert items
create policy "Users can insert their own items"
  on rebirth_items for insert
  with check ( auth.uid() = user_id );

-- 4. Storage Bucket Setup (for Images)
insert into storage.buckets (id, name, public) 
values ('rebirth_images', 'rebirth_images', true)
on conflict (id) do nothing;

-- 5. Storage Policies
-- Everyone can view images
create policy "Give public access to rebirth_images"
  on storage.objects for select
  using ( bucket_id = 'rebirth_images' );

-- Users can upload images
create policy "Allow validated uploads"
  on storage.objects for insert
  with check ( bucket_id = 'rebirth_images' and auth.role() = 'authenticated' );
